-- 코드를 입력하세요
SELECT a.TITLE, b.BOARD_ID, b.REPLY_ID,b.WRITER_ID,b.CONTENTS,date_format(b.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as a
inner join USED_GOODS_REPLY as b
on a.BOARD_ID = b.BOARD_ID
WHERE  SUBSTR(a.CREATED_DATE,1,7) = '2022-10'
order by b.CREATED_DATE ASC,a.title ASC;